# Generated by Django 3.2.19 on 2023-06-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEPT',
            fields=[
                ('DNO', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('DNAME', models.CharField(max_length=100)),
                ('DLOC', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENO', models.IntegerField(max_length=100)),
                ('ENAME', models.CharField(max_length=100)),
                ('EJOB', models.CharField(max_length=100)),
                ('DNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
